numeric_vector <- c(1.5, 2.7, 3.2, 4.9)
character_vector <- c("apple", "banana", "cherry", "date")
logical_vector <- c(TRUE, FALSE, TRUE, FALSE)
cat("Numeric Vector:\n")
print(numeric_vector)
cat("Character Vector:\n")
print(character_vector)
cat("Logical Vector:\n")
print(logical_vector)
